version: '3.9'

services:
  mariadb:
    container_name: cms_database
    image: mariadb:11.3.2
    ports:
      - ${DATABASE_EXPOSE}:3306
    volumes:
      - db_storage:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_USER_PASSWORD}
    networks:
      - backend_network

  cms_nestjs:
    container_name: cms_nestjs
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    build:
      context: ./
      dockerfile: ./Dockerfile.local
    volumes:
      - ./:/app
    networks:
      - backend_network
    depends_on:
      - mariadb

volumes:
  db_storage:
networks:
  backend_network:
