version: '3.9'

services:
  mariadb:
    container_name: cms_database
    restart: unless-stopped
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASe_USER}
      MARIADB_PASSWORD: ${DATABASE_USER_PASSWORD}
    networks:
      - backend_network

  cms_nestjs:
    container_name: cms_nestjs
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - backend_network
    depends_on:
      - mariadb

  httpd:
    container_name: proxy_server
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.httpd
    networks:
      - backend_network
    ports:
      - 80:80
    depends_on:
      - cms_nestjs

networks:
  backend_network:
