services:
  cms_nestjs:
    container_name: cms_nestjs
    restart: unless-stopped
    image: u7mica/crispy-cms:firsttry
    networks:
      - backend_network

  tepic_transita_server:
    container_name: tepic_transita_server
    restart: unless-stopped
    image: tepic-transita:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - /data/public:/app/public
    networks:
      - backend_network

  httpd:
    container_name: proxy_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.httpd
    networks:
      - backend_network
    ports:
      - 80:80
    depends_on:
      - cms_nestjs
      - tepic_transita_server

networks:
  backend_network:
